### PR TITLE
new golem ship

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

you ever do something and think, "How has nobody done this before?"

..well technically beestation already remapped the golem shuttle but this one is better so shhh
image

## Why It's Good For The Game

pretty golem ship

## Changelog
:cl:
add: Brand new golem ship!
/:cl:

### CODE REVIEW

**Comment by Maldaris** [comment]
Not to be a dick, but is there any reason this wouldn't be on the live repo?

**Comment by triplezeta** [comment]
honestly, not really. I can close this and open a PR on the live repo if you'd like.

**Comment by Maldaris** [comment]
Yeah that'd be great. Rather we keep the non WS related progress where it's visible for feedback.

**Comment by triplezeta** [comment]
understandable

**Pull request closed without merging**
